services:
  - type: web
    name: telegram-airport-bot
    runtime: docker
    plan: free
    region: oregon
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: PORT
        value: 3000
    dockerfilePath: ./Dockerfile
    dockerContext: .
